language: python

cache:
  - apt
  - pip

#install:
  #- python setup.py build_ext --inplace --zmq=$ZMQ
  #- sudo apt-get install -y gcc
  #- which python

matrix:
  include:
    - python: 3.7
      env: ZMQ=
      arch: arm64
      script: 
        - cd tools && invoke release 19.0.1
        - cd ../ && travis_retry python setup.py test 
    - python: 3.7
      env: ZMQ=bundled
      arch: arm64
      script: 
        - cd tools && invoke release 19.0.1
        - cd ../ && travis_retry python setup.py test 
    - python: 3.7
      env: ZMQ= 
      script: 
        - cd tools && invoke release 19.0.1
        - cd ../ && travis_retry python setup.py test 
    - python: 3.7
      env: ZMQ=bundled
      script: 
        - cd tools && invoke release 19.0.1
        - cd ../ && travis_retry python setup.py test 
    - os: osx
      language: python
      env: ZMQ=
      python: 3.7.8
      script: 
        - cd tools && invoke release 19.0.1
        - cd ../ && travis_retry python setup.py test 
        
script: travis_retry python setup.py test        
